services:
  tcljupyter:
    container_name: tcljupyter
    image: mpcjanssen/tcljupyter:arm64
    ports:
      - 127.0.0.1:7005:8888
    volumes:
      - notebooks:/home/tcljupyter/notebooks
      - config:/home/tcljupyter/config
      - libs:/home/tcljupyter/libs
    restart: unless-stopped
volumes:
  config:
  libs:
  notebooks:

