---
version: "2.1"
services:
  fossil:
    container_name: tcljupyter
    image: mpcjanssen/tcljupyter:latest
    ports:
      - "127.0.0.1:7005:8888"
    volumes:
      - data:/data
      - config:/config
    restart: unless-stopped
    
volumes:
   data:
   config:
