services:
  tcljupyter:
    container_name: tcljupyter
    image: mpcjanssen/tcljupyter:alpine
    ports:
      - "127.0.0.1:7005:8888"
    volumes:
      - notebooks:/notebooks
      - config:/config
    restart: unless-stopped
    
volumes:
   config:
   notebooks:
